"""View-model exports for the kiosk UI."""

from flower_vending.ui.viewmodels.common import ActionButtonViewModel, BannerTone, BannerViewModel
from flower_vending.ui.viewmodels.screens import (
    CatalogCategoryViewModel,
    CatalogItemViewModel,
    CatalogScreenViewModel,
    DeliveryScreenViewModel,
    DiagnosticsDeviceViewModel,
    DiagnosticsScreenViewModel,
    PaymentScreenViewModel,
    ProductDetailsScreenViewModel,
    ServiceScreenViewModel,
    StatusScreenViewModel,
    AdminAnalyticsTabViewModel,
    AdminCatalogItemViewModel,
    AdminCatalogTabViewModel,
    AdminOrderViewModel,
    AdminOrdersTabViewModel,
    AdminSettingsTabViewModel,
    AdminWindowViewModel,
    AdminWindowsTabViewModel,
)

__all__ = [
    "ActionButtonViewModel",
    "BannerTone",
    "BannerViewModel",
    "CatalogCategoryViewModel",
    "CatalogItemViewModel",
    "CatalogScreenViewModel",
    "DeliveryScreenViewModel",
    "DiagnosticsDeviceViewModel",
    "DiagnosticsScreenViewModel",
    "PaymentScreenViewModel",
    "ProductDetailsScreenViewModel",
    "ServiceScreenViewModel",
    "StatusScreenViewModel",
    "AdminAnalyticsTabViewModel",
    "AdminCatalogItemViewModel",
    "AdminCatalogTabViewModel",
    "AdminOrderViewModel",
    "AdminOrdersTabViewModel",
    "AdminSettingsTabViewModel",
    "AdminWindowViewModel",
    "AdminWindowsTabViewModel",
]
